---
# tasks file for cloudos-init
# author: lujianguo

- name: Include OS distribution variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags:  always

- import_tasks: 01.packages.yml 
  tags: package

- import_tasks: 02.services.yml 
  tags: service

- import_tasks: 03.tune.yml
  tags: tune

- import_tasks: 04.system-set.yml
  tags: system

